# -*- coding: utf-8 -*-
"""spline_generation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xKLOcgZD8FlS87chGB5yQ1iyopxRluV1
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow
import math
import array

class spline_generator:
  def __init__(self):
    
    self.img=cv2.imread("pic1.png")
    self.x=array.array('i',[])
    self.y=array.array('i',[])
    self.y.append(55)
    self.y.append(58)
    self.y.append(60)
    self.y.append(63)
    self.y.append(82)
    self.y.append(97)
    self.y.append(169)
    self.y.append(254)
    self.y.append(316)
    self.y.append(362)

    self.x.append(113)
    self.x.append(200)
    self.x.append(290)
    self.x.append(338)
    self.x.append(371)
    self.x.append(419)
    self.x.append(505)
    self.x.append(588)
    self.x.append(624)
    self.x.append(660)

    

  def spline(self):

    
    
    

  
          


s=spline_generator()
# s.spline()

